# Generated by Django 5.2.4 on 2025-07-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
