# Generated by Django 5.2.4 on 2025-07-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
