# Generated by Django 5.2.4 on 2025-07-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sport_type', models.CharField(choices=[('Team', 'Team'), ('Individual', 'Individual'), ('Dual', 'Dual'), ('Extreme', 'Extreme'), ('Other', 'Other')], max_length=50)),
                ('number_of_players', models.PositiveIntegerField(help_text='Number of players per team or individual')),
                ('origin_country', models.CharField(max_length=100)),
                ('equipment_required', models.TextField(blank=True)),
                ('rules', models.TextField(blank=True)),
                ('governing_body', models.CharField(blank=True, max_length=100)),
                ('popularity_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('olympic_sport', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='sports/')),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
    ]
