# Generated by Django 5.2.4 on 2025-07-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0004_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hostel_type', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Co-ed', 'Co-ed')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('warden_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('total_rooms', models.PositiveIntegerField()),
                ('available_rooms', models.PositiveIntegerField()),
                ('facilities', models.TextField(blank=True)),
                ('rules', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='hostels/')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
    ]
