# Generated by Django 5.2.4 on 2025-07-22 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0005_hostel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transport_type', models.CharField(choices=[('Bus', 'Bus'), ('Van', 'Van'), ('Car', 'Car'), ('Auto', 'Auto'), ('Other', 'Other')], max_length=20)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_contact', models.CharField(max_length=15)),
                ('route_details', models.TextField(blank=True)),
                ('available_timings', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='transports/')),
                ('associated_hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='others.hostel')),
            ],
        ),
    ]
