# Generated by Django 5.2.4 on 2025-07-26 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0006_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_cover',
        ),
    ]
