# Generated by Django 5.2.4 on 2025-07-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='YMsK1F6uyqIk51o1wP5m7Zs3TqQPsGWK', editable=False, max_length=32, unique=True),
        ),
    ]
