# Generated by Django 5.2.4 on 2025-07-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0004_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='uRB0UGEjngy88mFKQtRfhEhobpLWXOpJ', editable=False, max_length=32, unique=True),
        ),
    ]
