# Generated by Django 5.2.4 on 2025-07-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='RNTxnsmiAOPGebnpFPAeTn6BBNwkkWAP', editable=False, max_length=32, unique=True),
        ),
    ]
