# Generated by Django 5.2.4 on 2025-07-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0008_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='31fkgHM3AMTKOJgVn1nXX4eYN64eGC9D', editable=False, max_length=32, unique=True),
        ),
    ]
