# Generated by Django 5.2.4 on 2025-07-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0009_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='GT7DjC8td9hjvosX7mHUBoku2ZfyTeUH', editable=False, max_length=32, unique=True),
        ),
    ]
