# Generated by Django 5.2.4 on 2025-07-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0011_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='LKpTRiElBQUQFVMybLiALJeG5vq7QfBW', editable=False, max_length=32, unique=True),
        ),
    ]
