# Generated by Django 5.2.4 on 2025-07-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0013_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='E8lS7dBWwLP952S7DH0EDC3dLuwJDGX2', editable=False, max_length=32, unique=True),
        ),
    ]
