# Generated by Django 5.2.4 on 2025-07-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0016_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='QEWpw1liTy0q3jBPiaBSlbcFPdcnzPXO', editable=False, max_length=32, unique=True),
        ),
    ]
