# Generated by Django 5.2.4 on 2025-07-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0017_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='HQKqej6p4iH63vtD2Y1lsl8DlkAurnTb', editable=False, max_length=32, unique=True),
        ),
    ]
