# Generated by Django 5.2.4 on 2025-07-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0022_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='64PMOdwWv0DK0g6vsntAUgM63GdBxyAO', editable=False, max_length=32, unique=True),
        ),
    ]
