# Generated by Django 5.2.4 on 2025-07-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0023_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='hs3PSNBwH9aCIDQYZna2FWdJsn0A46vN', editable=False, max_length=32, unique=True),
        ),
    ]
