# Generated by Django 5.2.4 on 2025-07-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0024_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Jf9P80mJ3Q6zuwr9kM8tSkOJWT18e9RE', editable=False, max_length=32, unique=True),
        ),
    ]
