# Generated by Django 5.2.4 on 2025-07-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0027_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='2vX8zuqWvScUUDEvgaVIxeSbiwb68Pmj', editable=False, max_length=32, unique=True),
        ),
    ]
