# Generated by Django 5.2.4 on 2025-07-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0029_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='sRI0Cd7dw3cyLstpxtukVQvI5tJooC99', editable=False, max_length=32, unique=True),
        ),
    ]
