# Generated by Django 5.2.4 on 2025-07-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0032_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ovJWvIPgfvrvOZBExSMeGfFZ2w1G7EIo', editable=False, max_length=32, unique=True),
        ),
    ]
