# Generated by Django 5.2.4 on 2025-07-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0034_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='7rE3isksSZNhPGIe1Q4DEktb7lgJdrQO', editable=False, max_length=32, unique=True),
        ),
    ]
