# Generated by Django 5.2.4 on 2025-07-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0036_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Iay7WDM60IRLW7hT2GaM44IxbwVyMiBG', editable=False, max_length=32, unique=True),
        ),
    ]
