# Generated by Django 5.2.4 on 2025-07-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0041_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='LOlrtJwBInLjdqJ2cNpoi0B3ohQ3AB5E', editable=False, max_length=32, unique=True),
        ),
    ]
