# Generated by Django 5.2.4 on 2025-07-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0044_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='awTPvQXol5YMGnllfZzYF9gl6QLAzFv6', editable=False, max_length=32, unique=True),
        ),
    ]
