# Generated by Django 5.2.4 on 2025-07-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0050_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Dd9PV5uHDvHAr26hiIGwmtilqzAklHN0', editable=False, max_length=32, unique=True),
        ),
    ]
