# Generated by Django 5.2.4 on 2025-07-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0055_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='zvUsoY8ISVimDv8Me4ADEEcVJKvYUKYC', editable=False, max_length=32, unique=True),
        ),
    ]
