# Generated by Django 5.2.4 on 2025-07-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0057_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='HLBSkflRs3Icx8WAyw8BZYPGZGhDdn70', editable=False, max_length=32, unique=True),
        ),
    ]
