# Generated by Django 5.2.4 on 2025-07-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0061_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default-profile.png', null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='pb0jwQ7tRJOWe3sDxofxpzSB3Ks5nD7p', editable=False, max_length=32, unique=True),
        ),
    ]
