# Generated by Django 5.2.4 on 2025-07-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_code', models.CharField(max_length=20, unique=True)),
                ('event_type', models.CharField(choices=[('Seminar', 'Seminar'), ('Workshop', 'Workshop'), ('Conference', 'Conference'), ('Webinar', 'Webinar'), ('Social', 'Social'), ('Cultural', 'Cultural'), ('Sports', 'Sports'), ('Other', 'Other')], max_length=50)),
                ('department', models.CharField(choices=[('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('History', 'History'), ('Geography', 'Geography'), ('English', 'English'), ('Computer Science', 'Computer Science'), ('General', 'General')], max_length=100)),
                ('organizer', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
    ]
