# Generated by Django 5.2.4 on 2025-07-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('holiday_code', models.CharField(max_length=20, unique=True)),
                ('holiday_type', models.CharField(choices=[('Public', 'Public'), ('National', 'National'), ('Religious', 'Religious'), ('Cultural', 'Cultural'), ('Institutional', 'Institutional'), ('Other', 'Other')], max_length=50)),
                ('department', models.CharField(choices=[('All', 'All Departments'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('History', 'History'), ('Geography', 'Geography'), ('English', 'English'), ('Computer Science', 'Computer Science')], default='All', max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
    ]
